platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega2560__
        - ARDUINO_CI
        - __AVR__
      warnings:
      flags:

unittest:
  platforms:
    - mega2560

compile:
  platforms:
    - mega2560
